# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: patient.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'patient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpatient.proto\x12\x07patient\"$\n\x0ePatientRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\"<\n\x0fPatientResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t2U\n\x0ePatientService\x12\x43\n\x0eGetPatientInfo\x12\x17.patient.PatientRequest\x1a\x18.patient.PatientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'patient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATIENTREQUEST']._serialized_start=26
  _globals['_PATIENTREQUEST']._serialized_end=62
  _globals['_PATIENTRESPONSE']._serialized_start=64
  _globals['_PATIENTRESPONSE']._serialized_end=124
  _globals['_PATIENTSERVICE']._serialized_start=126
  _globals['_PATIENTSERVICE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
